ALTER TABLE fills ADD COLUMN IF NOT EXISTS fee_rate_bps NUMERIC(38, 18) NOT NULL DEFAULT 0;
ALTER TABLE fills ADD COLUMN IF NOT EXISTS trade_status TEXT NOT NULL DEFAULT 'CONFIRMED';
ALTER TABLE fills ADD COLUMN IF NOT EXISTS trader_side TEXT NOT NULL DEFAULT '';
ALTER TABLE order_intents ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'OPEN';